In [8]:
#Using Python list
import numpy as np
import time

size = 1_000_000

l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip (l1,l2)]
end = time.time()
print(add[0:20])

print(end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]
0.12061905860900879


In [4]:
l1=[1,2,3]

In [5]:
l2=[5,4,6]

In [6]:
list(zip(l1,l2))

[(1, 5), (2, 4), (3, 6)]

In [21]:
#Using numpy arrays
import numpy as np
import time

size = 1_000_000

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2

end = time.time()
print(add[0:20])

print(end - start)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
0.0035588741302490234


In [22]:
np.array([1,2,3,4,5,6])# 1 dimension array

array([1, 2, 3, 4, 5, 6])

In [12]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])# 3 dimension array

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr.shape

(3, 3)

In [18]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
print("Python list size:",sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:",numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [36]:
#Python list (loop-based)
list1 = [1,3,5,7,8,9]
start = time.time()
list_squares = [x ** 2 for x in list1]
end = time.time()
print("Time: ",(end-start))
print(list_squares)

Time:  0.00031757354736328125
[1, 9, 25, 49, 64, 81]


In [35]:
#Numpy (vectorized)
arr1 = np.array([1,2,3,4,5,6])
start = time.time()
numpy_squares = arr1**2
end = time.time()
print("Time: ",(end-start))
print(numpy_squares)

Time:  0.0
[ 1  4  9 16 25 36]
