In [3]:
import numpy as np
arr = np.array([1,3,5])

In [4]:
arr

array([1, 3, 5])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.arange(1,10,3)

array([1, 4, 7])

In [12]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [15]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [16]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [17]:
myarr.shape

(4, 3)

In [18]:
myarr.size

12

In [19]:
myarr.ndim

2

In [20]:
myarr.dtype

dtype('int64')

In [21]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]],dtype='float32')

In [22]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [23]:
myarr.astype('float64')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]])

In [24]:
myarr.dtype

dtype('float32')

In [25]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [26]:
myarr.shape

(4, 3)

In [27]:
reshaped = myarr.reshape((3,4))

In [28]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [29]:
myarr.reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 11],
       [12, 13]])

In [30]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])