In [1]:
import numpy as np
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [3]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [4]:
flat = myarr.flatten()

In [5]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [8]:
flat[0]

np.int64(1)

In [9]:
flat[3]

np.int64(4)

In [10]:
flat[3:7]

array([4, 5, 6, 7])

In [11]:
flat[-1]

np.int64(13)

In [12]:
flat[:6]

array([1, 2, 3, 4, 5, 6])

In [13]:
flat[6:]

array([ 7,  8,  9, 11, 12, 13])

In [15]:
flat[5::2]#Every second element

array([ 6,  8, 11, 13])

In [16]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [17]:
b = flat[3:7]

In [18]:
b

array([4, 5, 6, 7])

In [19]:
b[0] = 99

In [20]:
b

array([99,  5,  6,  7])

In [21]:
flat

array([ 1,  2,  3, 99,  5,  6,  7,  8,  9, 11, 12, 13])

In [22]:
arr = np.array([[16,23,32],[42,53,33],[74,85,96],[31,52,13]])

In [23]:
arr

array([[16, 23, 32],
       [42, 53, 33],
       [74, 85, 96],
       [31, 52, 13]])

In [40]:
b = arr[3:9].copy()# this is not a slice because we are using copy method to get the copy

In [36]:
b

array([[31, 52, 13]])

In [41]:
b[0]= 22

In [43]:
b

array([[22, 22, 22]])

In [47]:
arr

array([[16, 23, 32],
       [42, 53, 33],
       [74, 85, 96],
       [31, 52, 13]])

In [48]:
arr = np.array([1,45,67,85,34,87,49,7,9])

In [49]:
arr[[1,4,6]]

array([45, 34, 49])

In [50]:
arr[arr>34]

array([45, 67, 85, 87, 49])

In [51]:
num = np.array([1,2,3,4,5,6])

In [52]:
num

array([1, 2, 3, 4, 5, 6])

In [53]:
even = num[num%2==0]

In [54]:
even

array([2, 4, 6])

In [55]:
num.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])