In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[12 15 18]
[ 6 15 24]


In [3]:
print(np.average(arr, axis=0))

[4. 5. 6.]


In [4]:
arr [1][2]

np.int64(6)

In [5]:
arr[0,2]

np.int64(3)

In [6]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [8]:
#3D array
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3D.shape)

(2, 2, 3)


In [9]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
print(arr3D[0,1,2])

6


In [11]:
print(arr3D[:, 0, :])

[[1 2 3]
 [7 8 9]]


In [12]:
print(arr3D[0,0,:])

[1 2 3]


In [13]:
arr[:,0]

array([1, 4, 7])

In [14]:
arr3D[0,0,:]=0

In [15]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
arr3D[:,0,:] = 11

In [17]:
arr3D

array([[[11, 11, 11],
        [ 4,  5,  6]],

       [[11, 11, 11],
        [10, 11, 12]]])