In [2]:
#Looping Over Arrays in Python
import numpy as np

arr = np.array([1,2,3,4,5])
result = []

#Using a loop to square each element(slow)
for num in arr:
    result.append(num**2)
print(result)

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [3]:
#Vectorized Operation(fast)
arr = np.array([1,2,3,4,5])
result = arr ** 2
print(result)

[ 1  4  9 16 25]


In [4]:
result + 10

array([11, 14, 19, 26, 35])

In [6]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,20,30])

result = arr1 + arr2
print(result)

[[11 22 33]
 [14 25 36]]


In [7]:
#Normalizing Data Using Broadcasting
#Simulating a dataset (5 samples,3 features)
data = np.array([[10,20,30],
                [15,25,35],
                [20,30,40],
                [25,35,45],
                [30,40,50]])
mean = data.mean(axis=0)
std = data.std(axis=0)

normalized_data = (data - mean)/ std
print(normalized_data)


[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [8]:
mean

array([20., 30., 40.])

In [9]:
std

array([7.07106781, 7.07106781, 7.07106781])